name: folk
favicon: null
layout_spectrum: 0.2958285945933312
typography_spectrum: 0.7163869561627507
title: Folk
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5835376312024891
  lightness: 0.9815068405587226
  saturation: 0.2281892653554678
  rhythmicContrast: 0.8055686359293759
purpose: []
